/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Application {
  'id' : bigint,
  'courseChoice' : string,
  'name' : string,
  'email' : string,
  'phone' : string,
}
export interface ContactMessage {
  'id' : bigint,
  'name' : string,
  'email' : string,
  'message' : string,
}
export interface Course {
  'code' : string,
  'name' : string,
  'description' : string,
  'entryRequirements' : string,
}
export interface Grade {
  'subject' : string,
  'score' : bigint,
  'grade' : string,
}
export interface PersonalDetails { 'address' : string, 'phone' : string }
export interface StaffMember {
  'staffId' : string,
  'name' : string,
  'role' : string,
  'email' : string,
}
export interface Student {
  'grades' : Array<Grade>,
  'studentId' : string,
  'name' : string,
  'personalDetails' : PersonalDetails,
  'enrolledCourse' : string,
}
export interface _SERVICE {
  'getApplications' : ActorMethod<[], Array<Application>>,
  'getContactMessages' : ActorMethod<[], Array<ContactMessage>>,
  'getCourses' : ActorMethod<[], Array<Course>>,
  'getStaff' : ActorMethod<[], Array<StaffMember>>,
  'getStudent' : ActorMethod<[], Student>,
  'login' : ActorMethod<[string, string], [] | [Student]>,
  'submitApplication' : ActorMethod<[string, string, string, string], bigint>,
  'submitContactMessage' : ActorMethod<[string, string, string], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];