/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Application = IDL.Record({
  'id' : IDL.Nat,
  'courseChoice' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const ContactMessage = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
});
export const Course = IDL.Record({
  'code' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'entryRequirements' : IDL.Text,
});
export const StaffMember = IDL.Record({
  'staffId' : IDL.Text,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'email' : IDL.Text,
});
export const Grade = IDL.Record({
  'subject' : IDL.Text,
  'score' : IDL.Nat,
  'grade' : IDL.Text,
});
export const PersonalDetails = IDL.Record({
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const Student = IDL.Record({
  'grades' : IDL.Vec(Grade),
  'studentId' : IDL.Text,
  'name' : IDL.Text,
  'personalDetails' : PersonalDetails,
  'enrolledCourse' : IDL.Text,
});

export const idlService = IDL.Service({
  'getApplications' : IDL.Func([], [IDL.Vec(Application)], ['query']),
  'getContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
  'getCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'getStaff' : IDL.Func([], [IDL.Vec(StaffMember)], ['query']),
  'getStudent' : IDL.Func([], [Student], ['query']),
  'login' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(Student)], []),
  'submitApplication' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'submitContactMessage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Application = IDL.Record({
    'id' : IDL.Nat,
    'courseChoice' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const ContactMessage = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  const Course = IDL.Record({
    'code' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'entryRequirements' : IDL.Text,
  });
  const StaffMember = IDL.Record({
    'staffId' : IDL.Text,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'email' : IDL.Text,
  });
  const Grade = IDL.Record({
    'subject' : IDL.Text,
    'score' : IDL.Nat,
    'grade' : IDL.Text,
  });
  const PersonalDetails = IDL.Record({
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Student = IDL.Record({
    'grades' : IDL.Vec(Grade),
    'studentId' : IDL.Text,
    'name' : IDL.Text,
    'personalDetails' : PersonalDetails,
    'enrolledCourse' : IDL.Text,
  });
  
  return IDL.Service({
    'getApplications' : IDL.Func([], [IDL.Vec(Application)], ['query']),
    'getContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
    'getCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'getStaff' : IDL.Func([], [IDL.Vec(StaffMember)], ['query']),
    'getStudent' : IDL.Func([], [Student], ['query']),
    'login' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(Student)], []),
    'submitApplication' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'submitContactMessage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };